const data = {
  products: [
    {
      name: 'product-name',
      category: '',
      price: 100,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 15,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 20,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 60,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },

    {
      name: 'product-name',
      category: '',
      price: 100,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 15,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 20,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 60,
      token: 'product-token',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },
  ],
};
export default data;
