const data = {
  products: [
    {
      name: 'productA-name',
      category: '',
      price: 100,
      token: 'productA-token',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'productB-name',
      category: '',
      price: 15,
      token: 'productB-token',
      brand: 'Teva',
      countInStock: 0,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'productC-name',
      category: '',
      price: 20,
      token: 'productC-token',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'productD-name',
      category: '',
      price: 60,
      token: 'productD-token',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },

    {
      name: 'productE-name',
      category: '',
      price: 100,
      token: 'productE-token',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'productF-name',
      category: '',
      price: 15,
      token: 'productF-token',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'productG-name',
      category: '',
      price: 20,
      token: 'productG-token',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'productH-name',
      category: '',
      price: 60,
      token: 'productH-token',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },
  ],
};
export default data;
