import bcrypt from 'bcryptjs';

const data = {
  products: [
    {
      name: 'productA-name',
      category: 'Pharma',
      price: 100,
      token: 'productAtoken',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'productB-name',
      category: 'Pharma',
      price: 15,
      token: 'productBtoken',
      brand: 'Teva',
      countInStock: 0,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'productC-name',
      category: 'Pharma',
      price: 20,
      token: 'productCtoken',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'productD-name',
      category: 'Pharma',
      price: 60,
      token: 'productDtoken',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },

    {
      name: 'productE-name',
      category: 'Pharma',
      price: 100,
      token: 'productEtoken',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 80,
      description: 'liquid capsule',
      image: '/images/p1.jpeg',
    },
    {
      name: 'productFname',
      category: 'Pharma',
      price: 15,
      token: 'productF-token',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReviews: 100,
      description: 'liquid capsule',
      image: '/images/p2.jpeg',
    },
    {
      name: 'productG-name',
      category: 'Pharma',
      price: 20,
      token: 'productGtoken',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReviews: 13,
      description: 'liquid capsule',
      image: '/images/p3.jpeg',
    },
    {
      name: 'productH-name',
      category: 'Pharma',
      price: 60,
      token: 'productHtoken',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReviews: 10,
      description: 'liquid capsule',
      image: '/images/p4.jpeg',
    },
  ],

  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345'),
    },
  ],
};
export default data;
