const data = {
  products: [
    {
      name: 'product-name',
      category: '',
      price: 100,
      token: 'product-tokenq',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReview: 80,
      image: '/images/p1.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 15,
      token: 'product-tokenw',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReview: 100,
      image: '/images/p2.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 20,
      token: 'product-tokene',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReview: 13,
      image: '/images/p3.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 60,
      token: 'product-tokenr',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReview: 10,
      image: '/images/p4.jpeg',
    },

    {
      name: 'product-name',
      category: '',
      price: 100,
      token: 'product-tokenA',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReview: 80,
      image: '/images/p1.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 15,
      token: 'product-tokenB',
      brand: 'Teva',
      countInStock: 2,
      rating: 2.5,
      numReview: 100,
      image: '/images/p2.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 20,
      token: 'product-tokenC',
      brand: 'Teva',
      countInStock: 12,
      rating: 2.5,
      numReview: 13,
      image: '/images/p3.jpeg',
    },
    {
      name: 'product-name',
      category: '',
      price: 60,
      token: 'product-tokenD',
      brand: 'Teva',
      countInStock: 4,
      rating: 2.5,
      numReview: 10,
      image: '/images/p4.jpeg',
    },
  ],
};
export default data;
